- name: Installing packages laptop
  apt:
    name:
      - tlp 
      - gimp 
      - openvpn
      - torbrowser-launcher 
      - blueman 
      - telegram-desktop 
      - remmina 
      - firmware-misc-nonfree

- name: Add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install MakeMKV
  flatpak:
    name: com.makemkv.MakeMKV
    state: absent 
    method: user

- name: Installing flatpak packages laptop
  flatpak:
    name: 
     - org.videolan.VLC
     - org.signal.Signal
     - org.libretro.RetroArch

        #others: exodus, syncient, PlexAmp appimage from plex
