- name: Installing packages laptop
  apt:
    name:
      - tlp 
      - gimp 
      - openvpn
      - torbrowser-launcher 
      - blueman 
      - telegram-desktop 
      - remmina 
      - firmware-misc-nonfree
  tags: laptop
  
- name: Add flathub repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Installing system flatpaks
  flatpak:
    name: org.libretro.RetroArch

- name: Installing Signal
  flatpak:
    name: org.signal.Signal
    
- name: Set gedit scheme
  #    become_user: walchst 
    #      dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc'"
  dconf: key="/org/gnome/gedit/preferences/editor/scheme" value="'cobalt'"
      
        #others: exodus, syncient, PlexAmp appimage from plex
